/*
__G__ = "(G)bd249ce4"
*/

rule VirusDetectionGeneric
{
strings:
    $ = "360hotfix.exe" wide nocase ascii
    $ = "360rpt.exe" wide nocase ascii
    $ = "360safe.exe" wide nocase ascii
    $ = "360safebox.exe" wide nocase ascii
    $ = "360tray.exe" wide nocase ascii
    $ = "agentsvr.exe" wide nocase ascii
    $ = "apvxdwin.exe" wide nocase ascii
    $ = "ast.exe" wide nocase ascii
    $ = "avcenter.exe" wide nocase ascii
    $ = "avengine.exe" wide nocase ascii
    $ = "avgnt.exe" wide nocase ascii
    $ = "avguard.exe" wide nocase ascii
    $ = "avltmain.exe" wide nocase ascii
    $ = "avp.exe" wide nocase ascii
    $ = "avp32.exe" wide nocase ascii
    $ = "avtask.exe" wide nocase ascii
    $ = "bdagent.exe" wide nocase ascii
    $ = "bdwizreg.exe" wide nocase ascii
    $ = "boxmod.exe" wide nocase ascii
    $ = "ccapp.exe" wide nocase ascii
    $ = "ccenter.exe" wide nocase ascii
    $ = "ccevtmgr.exe" wide nocase ascii
    $ = "ccregvfy.exe" wide nocase ascii
    $ = "ccsetmgr.exe" wide nocase ascii
    $ = "egui.exe" wide nocase ascii
    $ = "ekrn.exe" wide nocase ascii
    $ = "extdb.exe" wide nocase ascii
    $ = "frameworkservice.exe" wide nocase ascii
    $ = "frwstub.exe" wide nocase ascii
    $ = "guardfield.exe" wide nocase ascii
    $ = "iparmor.exe" wide nocase ascii
    $ = "kaccore.exe" wide nocase ascii
    $ = "kasmain.exe" wide nocase ascii
    $ = "kav32.exe" wide nocase ascii
    $ = "kavstart.exe" wide nocase ascii
    $ = "kavsvc.exe" wide nocase ascii
    $ = "kavsvcui.exe" wide nocase ascii
    $ = "kislnchr.exe" wide nocase ascii
    $ = "kissvc.exe" wide nocase ascii
    $ = "kmailmon.exe" wide nocase ascii
    $ = "knownsvr.exe" wide nocase ascii
    $ = "kpfw32.exe" wide nocase ascii
    $ = "kpfwsvc.exe" wide nocase ascii
    $ = "kregex.exe" wide nocase ascii
    $ = "kvfw.exe" wide nocase ascii
    $ = "kvmonxp.exe" wide nocase ascii
    $ = "kvol.exe" wide nocase ascii
    $ = "kvprescan.exe" wide nocase ascii
    $ = "kvsrvxp.exe" wide nocase ascii
    $ = "kvwsc.exe" wide nocase ascii
    $ = "kwatch.exe" wide nocase ascii
    $ = "livesrv.exe" wide nocase ascii
    $ = "makereport.exe" wide nocase ascii
    $ = "mcagent.exe" wide nocase ascii
    $ = "mcdash.exe" wide nocase ascii
    $ = "mcdetect.exe" wide nocase ascii
    $ = "mcshield.exe" wide nocase ascii
    $ = "mctskshd.exe" wide nocase ascii
    $ = "mcvsescn.exe" wide nocase ascii
    $ = "mcvsshld.exe" wide nocase ascii
    $ = "mghtml.exe" wide nocase ascii
    $ = "naprdmgr.exe" wide nocase ascii
    $ = "navapsvc.exe" wide nocase ascii
    $ = "navapw32.exe" wide nocase ascii
    $ = "navw32.exe" wide nocase ascii
    $ = "nmain.exe" wide nocase ascii
    $ = "nod32.exe" wide nocase ascii
    $ = "nod32krn.exe" wide nocase ascii
    $ = "nod32kui.exe" wide nocase ascii
    $ = "npfmntor.exe" wide nocase ascii
    $ = "oasclnt.exe" wide nocase ascii
    $ = "pavsrv51.exe" wide nocase ascii
    $ = "pfw.exe" wide nocase ascii
    $ = "psctrls.exe" wide nocase ascii
    $ = "psimreal.exe" wide nocase ascii
    $ = "psimsvc.exe" wide nocase ascii
    $ = "qqdoctormain.exe" wide nocase ascii
    $ = "ras.exe" wide nocase ascii
    $ = "ravmon.exe" wide nocase ascii
    $ = "ravmond.exe" wide nocase ascii
    $ = "ravstub.exe" wide nocase ascii
    $ = "ravtask.exe" wide nocase ascii
    $ = "rfwcfg.exe" wide nocase ascii
    $ = "rfwmain.exe" wide nocase ascii
    $ = "rfwproxy.exe" wide nocase ascii
    $ = "rfwsrv.exe" wide nocase ascii
    $ = "rsagent.exe" wide nocase ascii
    $ = "rsmain.exe" wide nocase ascii
    $ = "rsnetsvr.exe" wide nocase ascii
    $ = "rssafety.exe" wide nocase ascii
    $ = "rstray.exe" wide nocase ascii
    $ = "safebank.exe" wide nocase ascii
    $ = "safeboxtray.exe" wide nocase ascii
    $ = "scan32.exe" wide nocase ascii
    $ = "scanfrm.exe" wide nocase ascii
    $ = "sched.exe" wide nocase ascii
    $ = "seccenter.exe" wide nocase ascii
    $ = "secnotifier.exe" wide nocase ascii
    $ = "SetupLD.exe" wide nocase ascii
    $ = "shstat.exe" wide nocase ascii
    $ = "smartup.exe" wide nocase ascii
    $ = "sndsrvc.exe" wide nocase ascii
    $ = "spbbcsvc.exe" wide nocase ascii
    $ = "symlcsvc.exe" wide nocase ascii
    $ = "tbmon.exe" wide nocase ascii
    $ = "uihost.exe" wide nocase ascii
    $ = "ulibcfg.exe" wide nocase ascii
    $ = "updaterui.exe" wide nocase ascii
    $ = "uplive.exe" wide nocase ascii
    $ = "vcr32.exe" wide nocase ascii
    $ = "vcrmon.exe" wide nocase ascii
    $ = "vptray.exe" wide nocase ascii
    $ = "vsserv.exe" wide nocase ascii
    $ = "vstskmgr.exe" wide nocase ascii
    $ = "webproxy.exe" wide nocase ascii
    $ = "xcommsvr.exe" wide nocase ascii
    $ = "xnlscn.exe" wide nocase ascii

    $ = "Application Data\\Agnitum" wide nocase ascii
    $ = "Application Data\\avg10" wide nocase ascii
    $ = "Application Data\\avg8" wide nocase ascii
    $ = "Application Data\\avg9" wide nocase ascii
    $ = "Application Data\\Avira" wide nocase ascii
    $ = "Application Data\\Doctor Web" wide nocase ascii
    $ = "Application Data\\ESET" wide nocase ascii
    $ = "Application Data\\f-secure" wide nocase ascii
    $ = "Application Data\\G DATA" wide nocase ascii
    $ = "Application Data\\Kaspersky Lab" wide nocase ascii
    $ = "Application Data\\McAfee" wide nocase ascii
    $ = "Application Data\\Microsoft\\Microsoft Antimalware" wide nocase ascii
    $ = "Application Data\\PC Tools" wide nocase ascii
    $ = "Application Data\\Symantec" wide nocase ascii
    $ = "Application Data\\Trend Micro" wide nocase ascii
    $ = "All Users\\AVAST Software" wide nocase ascii
    $ = "Local SettingsApplication Data\\F-Secure" wide nocase ascii

    $ = "Program Files\\Agnitum" wide nocase ascii
    $ = "Program Files\\Alwil Software" wide nocase ascii
    $ = "Program Files\\AVAST Software" wide nocase ascii
    $ = "Program Files\\AVG" wide nocase ascii
    $ = "Program Files\\Avira" wide nocase ascii
    $ = "Program Files\\BitDefender9" wide nocase ascii
    $ = "Program Files\\Common Files\\Doctor Web" wide nocase ascii
    $ = "Program Files\\Common Files\\G DATA" wide nocase ascii
    $ = "Program Files\\Common Files\\PC Tools" wide nocase ascii
    $ = "Program Files\\DrWeb" wide nocase ascii
    $ = "Program Files\\ESET" wide nocase ascii
    $ = "Program Files\\F-Secure Internet Security" wide nocase ascii
    $ = "Program Files\\FRISK Software" wide nocase ascii
    $ = "Program Files\\Kaspersky Lab" wide nocase ascii
    $ = "Program Files\\McAfee" wide nocase ascii
    $ = "Program Files\\Microsoft Security Essentials" wide nocase ascii
    $ = "Program Files\\Norton AntiVirus" wide nocase ascii
    $ = "Program Files\\Panda Security" wide nocase ascii
    $ = "Program Files\\PC Tools Internet Security" wide nocase ascii
    $ = "Program Files\\Symantec" wide nocase ascii
    $ = "Program Files\\Trend Micro" wide nocase ascii
    $ = "Program Files\\Vba32" wide nocase ascii

    $ = "Program Files (x86)\\Agnitum" wide nocase ascii
    $ = "Program Files (x86)\\Alwil Software" wide nocase ascii
    $ = "Program Files (x86)\\AVAST Software" wide nocase ascii
    $ = "Program Files (x86)\\AVG" wide nocase ascii
    $ = "Program Files (x86)\\Avira" wide nocase ascii
    $ = "Program Files (x86)\\BitDefender9" wide nocase ascii
    $ = "Program Files (x86)\\Common Files\\Doctor Web" wide nocase ascii
    $ = "Program Files (x86)\\Common Files\\G DATA" wide nocase ascii
    $ = "Program Files (x86)\\Common Files\\PC Tools" wide nocase ascii
    $ = "Program Files (x86)\\DrWeb" wide nocase ascii
    $ = "Program Files (x86)\\ESET" wide nocase ascii
    $ = "Program Files (x86)\\F-Secure Internet Security" wide nocase ascii
    $ = "Program Files (x86)\\Kaspersky Lab" wide nocase ascii
    $ = "Program Files (x86)\\McAfee" wide nocase ascii
    $ = "Program Files (x86)\\Microsoft Security Essentials" wide nocase ascii
    $ = "Program Files (x86)\\Norton AntiVirus" wide nocase ascii
    $ = "Program Files (x86)\\Panda Security" wide nocase ascii
    $ = "Program Files (x86)\\PC Tools Internet Security" wide nocase ascii
    $ = "Program Files (x86)\\Symantec" wide nocase ascii
    $ = "Program Files (x86)\\Trend Micro" wide nocase ascii
    $ = "Program Files (x86)\\Vba32" wide nocase ascii

condition:
    any of them
}
